flowchart TD
    A[开始] --> B[初始化数据]
    B --> C[分配GPU内存]
    C --> D[复制数据到GPU]
    D --> E[启动计时器]
    E --> F[调用max_soft内核]
    F --> G[调用gridmax内核]
    G --> H[调用sum_soft内核]
    H --> I[调用gridsum内核]
    I --> J[调用softmax内核]
    J --> K[停止计时器]
    K --> L[复制结果回CPU]
    L --> M[释放GPU内存]
    M --> N[结束]